language: ruby
rvm:
- 2.2.2

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

install:
- npm install gitbook-cli -g
- gitbook install
- gitbook build
- gem install html-proofer

script: 

- htmlproofer ./_book --empty-alt-ignore true --check-external-hash true --url-ignore 'https://utm.arc.nasa.gov/,https://groups.google.com/forum/#!forum/uavcan'


env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true   # speeds up installation of html-proofer

## Allow links to fail any time and be displayed as warnings.
matrix:
  allow_failures:
    - rvm: 2.2.2
